# -*- coding: utf-8 -*-
"""GS_PCP.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qmDMYOfoCYBRJk4_1hEwegym3rWjyN-D
"""

#nome da missao e da equipe
nome_missao = "Solar"
nome_equipe = "Equipe Apollo"

# mostrar informações principais antes da análise dos ciclos
print("Missão:", nome_missao)
print("Equipe:", nome_equipe)
print("6 Ciclos foram analisados")


# as 6 linhas representa cada ciclo da missão e a ordem de cada coluna é [temperatura, comunicação, bateria, oxigênio, estabilidade]
dados_missao = [
    [24, 92, 88, 96, 90],
    [27, 80, 72, 94, 85],
    [31, 65, 58, 91, 70],
    [36, 42, 38, 87, 55],
    [39, 28, 19, 78, 35],
    [34, 55, 32, 82, 50]
]

# lista com os nomes das áreas monitoradas
areas_monitoradas = [
    "Temperatura interna",
    "Comunicação com a base",
    "Sistema de energia",
    "Suporte de oxigênio",
    "Estabilidade operacional"
]


# função que analisa a temperatura
# ela recebe um valor e retorna a classificação, a pontuação e uma mensagem
def analisar_temperatura(valor):
    # se a temperatura for menor que 18, está abaixo do ideal
    if valor < 18:
        return "ATENÇÃO", 1, "Temperatura muito baixa"

    # Se estiver entre 18 e 30, está normal
    elif valor <= 30:
        return "NORMAL", 0, "Temperatura estável"

    # Se estiver entre 31 e 35, precisa de atenção
    elif valor <= 35:
        return "ATENÇÃO", 1, "Temperatura elevada"

    # Se for maior que 35, é considerado crítico
    else:
        return "CRÍTICO", 2, "Risco de superaquecimento"


# função que analisa a comunicação com a base
def analisar_comunicacao(valor):
    # comunicação abaixo de 30% é crítica
    if valor < 30:
        return "CRÍTICO", 2, "Comunicação com a base em nível crítico"

    # comunicação entre 30% e 59% precisa de atenção
    elif valor <= 59:
        return "ATENÇÃO", 1, "Comunicação instável"

    # comunicação com 60% ou mais está normal
    else:
        return "NORMAL", 0, "Comunicação estável"


# função que analisa o nível da bateria
def analisar_bateria(valor):
    # bateria abaixo de 20% é crítica
    if valor < 20:
        return "CRÍTICO", 2, "Bateria em nível crítico"

    # bateria entre 20% e 49% precisa de atenção
    elif valor <= 49:
        return "ATENÇÃO", 1, "Bateria abaixo do recomendado"

    # Bateria com 50% ou mais está normal
    else:
        return "NORMAL", 0, "Energia estável"


# função que analisa o nível de oxigênio
def analisar_oxigenio(valor):
    # oxigênio abaixo de 80% é crítico
    if valor < 80:
        return "CRÍTICO", 2, "Oxigênio em nível crítico"

    # oxigênio entre 80% e 89% é abaixo do ideal
    elif valor <= 89:
        return "ATENÇÃO", 1, "Oxigênio abaixo do ideal, precisa de atenção"

    # oxigênio com 90% ou mais está normal
    else:
        return "NORMAL", 0, "Oxigênio adequado"


# função que analisa a estabilidade geral da missão
def analisar_estabilidade(valor):
    # estabilidade abaixo de 40% é crítica
    if valor < 40:
        return "CRÍTICO", 2, "Estabilidade operacional crítica"

    # estabilidade entre 40% e 69% precisa de atenção
    elif valor <= 69:
        return "ATENÇÃO", 1, "Estabilidade operacional reduzida"

    # estabilidade com 70% ou mais está normal
    else:
        return "NORMAL", 0, "Estabilidade operacional adequada"


# função que classifica o ciclo de acordo com a soma dos pontos
def classificar_ciclo(pontos):
    # de 0 a 2 pontos, o ciclo está estável
    if pontos <= 2:
        return "MISSÃO ESTÁVEL"

    # de 3 a 5 pontos, o ciclo está em atenção
    elif pontos <= 5:
        return "MISSÃO EM ATENÇÃO"

    # de 6 a 10 pontos, o ciclo está crítico
    else:
        return "MISSÃO CRÍTICA"


# função que gera uma recomendação com base na pontuação do ciclo
def gerar_recomendacao(pontos):
    # funcionamento normal
    if pontos <= 2:
        return "Manter operação normal e continuar monitoramento!."

    # necessita monitoração
    elif pontos <= 5:
        return "Monitorar sistemas em atenção e preparar plano de contingência!."

    # situação crítica
    else:
        return "Ativar modo de segurança e priorizar energia, comunicação e suporte!."


# comparando o primeiro risco com o último risco definindo se a missão melhorou ou piorou
def analisar_tendencia(riscos):
    if riscos[-1] > riscos[0]:
        return "A missão apresentou tendência de piora."

    elif riscos[-1] < riscos[0]:
        return "A missão apresentou tendência de melhora."

    else:
        return "A missão permaneceu estável em relação ao início."


# identificando qual área teve maior soma de risco
def identificar_area_mais_afetada(riscos_por_area):
    maior_risco = max(riscos_por_area)

    # descobrindo a posição desse maior valor na lista
    posicao = riscos_por_area.index(maior_risco)

    return areas_monitoradas[posicao]


# analisando e mostrando um ciclo completo
def mostrar_ciclo(numero, ciclo, riscos_por_area):
    # separando os valores do ciclo para facilitar o uso no código
    temperatura = ciclo[0]
    comunicacao = ciclo[1]
    bateria = ciclo[2]
    oxigenio = ciclo[3]
    estabilidade = ciclo[4]

    # analisando cada valor usando sua função específica
    temp_status, temp_pontos, temp_msg = analisar_temperatura(temperatura)
    com_status, com_pontos, com_msg = analisar_comunicacao(comunicacao)
    bat_status, bat_pontos, bat_msg = analisar_bateria(bateria)
    oxi_status, oxi_pontos, oxi_msg = analisar_oxigenio(oxigenio)
    est_status, est_pontos, est_msg = analisar_estabilidade(estabilidade)

    # somando todos os pontos para descobrir o risco total do ciclo
    pontos_ciclo = temp_pontos + com_pontos + bat_pontos + oxi_pontos + est_pontos

    # somando a pontuação de cada área para usar depois no relatório final
    riscos_por_area[0] += temp_pontos
    riscos_por_area[1] += com_pontos
    riscos_por_area[2] += bat_pontos
    riscos_por_area[3] += oxi_pontos
    riscos_por_area[4] += est_pontos

    # mostrando as informações do ciclo no terminal
    print("\nCICLO", numero)
    print("====================================")
    print("Temperatura:", temperatura, "°C |", temp_status, "|", temp_msg)
    print("Comunicação:", comunicacao, "% |", com_status, "|", com_msg)
    print("Bateria:", bateria, "% |", bat_status, "|", bat_msg)
    print("Oxigênio:", oxigenio, "% |", oxi_status, "|", oxi_msg)
    print("Estabilidade:", estabilidade, "% |", est_status, "|", est_msg)
    print("Pontuação de risco do ciclo:", pontos_ciclo)
    print("Classificação do ciclo:", classificar_ciclo(pontos_ciclo))
    print("Recomendação:", gerar_recomendacao(pontos_ciclo))

    # retornando a pontuação do ciclo para ser guardada na lista riscos
    return pontos_ciclo


# gerando o relatório final depois das analises dos ciclos
def gerar_relatorio_final(riscos, riscos_por_area):
    # listas feitas para armazenar separadamente os dados de cada área
    temperaturas = []
    comunicacoes = []
    baterias = []
    oxigenios = []
    estabilidades = []

    # percorre todos os ciclos e separa os dados em listas específicas
    for ciclo in dados_missao:
        temperaturas.append(ciclo[0])
        comunicacoes.append(ciclo[1])
        baterias.append(ciclo[2])
        oxigenios.append(ciclo[3])
        estabilidades.append(ciclo[4])

    # encontrando o maior risco registrado
    maior_risco = max(riscos)

    # identificando o ciclo mais crítico
    ciclo_mais_critico = riscos.index(maior_risco) + 1 # + 1 porque a lista começa na posição 0

    # calculando o risco médio da missão
    risco_medio = sum(riscos) / len(riscos)

    # contagem de ciclos críticos
    ciclos_criticos = 0
    for risco in riscos:
        if risco >= 6:
            ciclos_criticos += 1

    # relatório final
    print("\nRELATÓRIO:")
    print("\nMédia de temperatura:", round(sum(temperaturas) / len(temperaturas), 2), "°C")
    print("Média de comunicação:", round(sum(comunicacoes) / len(comunicacoes), 2), "%")
    print("Média de bateria:", round(sum(baterias) / len(baterias), 2), "%")
    print("Média de oxigênio:", round(sum(oxigenios) / len(oxigenios), 2), "%")
    print("Média de estabilidade:", round(sum(estabilidades) / len(estabilidades), 2), "%")
    print("Ciclo mais crítico: Ciclo", ciclo_mais_critico)
    print("Maior pontuação de risco:", maior_risco)
    print("Risco médio da missão:", round(risco_medio, 2))
    print("Quantidade de ciclos críticos:", ciclos_criticos)
    print("Tendência da missão:", analisar_tendencia(riscos))

    # pontuação acumulada de risco em cada área
    print("\nPontuação acumulada por área:")
    for i in range(len(areas_monitoradas)):
        print(areas_monitoradas[i] + ":", riscos_por_area[i], "pontos")

    # mostra área mais afetada durante a missão
    print("\nÁrea mais afetada:", identificar_area_mais_afetada(riscos_por_area))

    # mostra a classificação final usando o risco médio
    print("\nClassificação final da missão:")
    print(classificar_ciclo(round(risco_medio)))

    # conclusão de acordo com o risco médio
    print("\nConclusão:")
    if risco_medio <= 2:
        print("A missão está estável e pode continuar normalmente.")
    elif risco_medio <= 5:
        print("A missão exige atenção, mas ainda pode ser controlada.")
    else:
        print("A missão está crítica e precisa de ações imediatas.")


# lista que vai guardar a pontuação de risco de cada ciclo
riscos = []

# lista que vai guardar a soma de risco de cada área monitorada
# começa com zero porque nenhuma área foi analisada ainda
riscos_por_area = [0, 0, 0, 0, 0]

# percorre todos os ciclos da matriz dados_missao
for i in range(len(dados_missao)):
    risco = mostrar_ciclo(i + 1, dados_missao[i], riscos_por_area)

    # guarda o risco calculado na lista de riscos
    riscos.append(risco)

# gerar o relatório final
gerar_relatorio_final(riscos, riscos_por_area)